Design property
navikt/crm-shared-timeline pull request #106
Opened 2024-12-20 07:37 UTC by mamikals

2024-12-20 07:41 UTC, mamikals reviewed
Jeg merget inn #104 til denne branchen så alt kunne ses på med en gang, men hadde noen kommentarer på den som jeg skriver her. Jeg tok også bort showSubtitle propertyen, jeg er ikke sikker på hva den skulle gjøre?

2024-12-20 07:41 UTC, mamikals commented on force-app/main/default/lwc/timeline/timeline.js
> +    }
Den her metoden gjør jo noe helt annet en den originale, hvor ble det av amountOfMonthsToLoad?

2024-12-20 07:41 UTC, mamikals commented on force-app/main/default/lwc/timelineItem/slick.html
> +                                </template>
Her er rekkefølgen feil, relatedUser kommer før subtitle, som er feil

2024-12-23 11:12 UTC, vegarduri requested changes
Ser bra ut :) Har noen små kommentarer som egentlig bare er forslag.

2024-12-23 11:12 UTC, vegarduri commented on force-app/main/default/lwc/timelineGroup/timelineGroup.js
> +    get iconPath() {
Er det bedre å bruke CSS til dette?

2024-12-23 11:12 UTC, vegarduri commented on force-app/main/default/lwc/timelineItem/timelineItem.js
> +    render() {
Kan gjøre det på samme måte som du har gjort for de andre
   
   render() {
        return this.design === 'Slick' ? slickLayout : defaultLayout;
    }

2024-12-23 11:12 UTC, vegarduri commented on force-app/main/default/lwc/timelineItem/timelineItem.js
> +        if(this.row.record.clampLines != null) return '--lwc-lineClamp: ' + this.row.record.clampLines;
forslag:    return this.row.record.clampLines != null ? `--lwc-lineClamp: ${this.row.record.clampLines}` : null eller undefined;

2025-01-07 07:06 UTC, mamikals commented on force-app/main/default/classes/Timeline_Model.cls
> +        record.clampLines = (Integer) config.Timeline_Child__r.ClampLines__c;
Ja det blir dekket av de gamle testene, så vi får faktisk økt testdekningsgrad. Men det er ikke lagt inn nye tester for selve funksjonaliteten da

2025-01-07 07:07 UTC, mamikals commented on force-app/main/default/lwc/timeline/timeline.js-meta.xml
> +                label="Select the design varient" datasource="Default,Slick" />
Ja helt enig, jeg er ikke særlig glad i det selv, så jeg tar gjerne imot bedre forslag hehe

2025-01-07 07:07 UTC, mamikals commented on force-app/main/default/lwc/timelineDate/timelineDate.js
> +        } catch (error) {
Nei, vil ikke

2025-01-07 07:08 UTC, mamikals commented on force-app/main/default/lwc/timelineGroup/slick.html
> +        <div class="slds-accordion__summary slds-var-p-bottom_small">
Det har jeg ikke, jeg visste faktisk ikke om var-p vs. vanlig p før i går faktisk 😄, men jeg ser på det når vi gjør full testen i SIT2 tenker jeg

2025-01-07 08:53 UTC, mamikals commented on force-app/main/default/lwc/timelineGroup/timelineGroup.js
> +    get iconPath() {
Det er nok bedre å bruke CSS ja, jeg fikser

2025-01-07 08:55 UTC, mamikals commented on force-app/main/default/lwc/timelineItem/timelineItem.js
> +    render() {
Ja, planen min med å gjøre det slik originalt var for å støtte flere nye design hvis andre ville det, men det kan fikses da hvis det er ønskelig. Det er bedre med dette nå 😄

2025-01-07 09:01 UTC, mamikals commented on force-app/main/default/lwc/timelineItem/timelineItem.js
> +        if(this.row.record.clampLines != null) return '--lwc-lineClamp: ' + this.row.record.clampLines;
Smart

2025-01-07 14:07 UTC, EirikFladby approved these changes
Godt stykke arbeid, Herr Marton! 🥇

2025-01-08 07:38 UTC, mamikals commented on force-app/main/default/lwc/timeline/timeline.js-meta.xml
> +                label="Select the design varient" datasource="Default,Slick" />
Jeg liker ikke det fordi dette er jo i teorien et "vanlig" design som andre team skal unne ta i bruk, jeg tror POAB har spurt om det f.eks.

2025-01-08 07:39 UTC, mamikals commented on force-app/main/default/classes/Timeline_Helper.cls
> -                name += ' (' + modelsSeparatedByMonth.get(key).size() + ')';
Jeg husker ikke 100%, men jeg tror det er fordi Sara flyttet det til Javascript delen

2025-01-08 07:43 UTC, mamikals commented on force-app/main/default/lwc/timelineDate/timelineDate.js
> +        }
Sure, det er mye mer leselig iallfall, jeg kopierte egentlig bare koden fra timelineItem.js og levde med det 😄

2025-01-08 13:20 UTC, saramoh2309 commented on force-app/main/default/classes/Timeline_Helper.cls
> -                name += ' (' + modelsSeparatedByMonth.get(key).size() + ')';
Tallet vist derfra ble ikke oppdatert etter filtrering eller refresh fordi listen blir oppdatert i js, så det er flyttet der

2025-01-21 15:13 UTC, merged